/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package MIKA;

import MIKA.INSERTMenuItem;

/**
 *
 * @author IRIS
 */
public class INSERT extends javax.swing.JFrame {

    /**
     * Creates new form MikaGUI
     */
    public INSERT() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        jPopupMenu2 = new javax.swing.JPopupMenu();
        jPopupMenu3 = new javax.swing.JPopupMenu();
        jPopupMenu4 = new javax.swing.JPopupMenu();
        Main = new javax.swing.JTabbedPane();
        Insert = new javax.swing.JPanel();
        InsertLabel = new javax.swing.JLabel();
        InsertEntity = new javax.swing.JComboBox<>();
        SubmitEntity = new javax.swing.JButton();
        INSERTExit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("INSERT");

        InsertLabel.setText("Insert new data into:");

        InsertEntity.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Receipt", "Menu Item", "Ingredient", "Shipment", "Employee", "Shift" }));
        InsertEntity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InsertEntityActionPerformed(evt);
            }
        });

        SubmitEntity.setText("Submit");
        SubmitEntity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitEntityActionPerformed(evt);
            }
        });

        INSERTExit.setText("Exit");
        INSERTExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                INSERTExitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout InsertLayout = new javax.swing.GroupLayout(Insert);
        Insert.setLayout(InsertLayout);
        InsertLayout.setHorizontalGroup(
            InsertLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InsertLayout.createSequentialGroup()
                .addGroup(InsertLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(InsertLayout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(InsertLabel))
                    .addGroup(InsertLayout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(InsertEntity, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(48, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, InsertLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(InsertLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(INSERTExit)
                    .addComponent(SubmitEntity))
                .addGap(138, 138, 138))
        );
        InsertLayout.setVerticalGroup(
            InsertLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InsertLayout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(InsertLabel)
                .addGap(18, 18, 18)
                .addComponent(InsertEntity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(SubmitEntity)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                .addComponent(INSERTExit)
                .addGap(33, 33, 33))
        );

        Main.addTab("Insert", Insert);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Main)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Main, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SubmitEntityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitEntityActionPerformed
        String entity = InsertEntity.getSelectedItem().toString();
        switch(entity)
        {
            case "Receipt":
            new INSERTReceipt().setVisible(true);
            break;
            case "Menu Item":
            new INSERTMenuItem().setVisible(true);
            break;
            case "Ingredient":
            new INSERTIngredient().setVisible(true);
            break;
            case "Shipment":
            new INSERTShipment().setVisible(true);
            break;
            case "Employee":
            new INSERTEmployee().setVisible(true);
            break;
            case "Shift":
            new INSERTEmployeeShift().setVisible(true);
            break;
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_SubmitEntityActionPerformed

    private void InsertEntityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InsertEntityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InsertEntityActionPerformed

    private void INSERTExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_INSERTExitActionPerformed
        // TODO add your handling code here:
        //this.dispose();
    }//GEN-LAST:event_INSERTExitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(INSERT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(INSERT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(INSERT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(INSERT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new INSERT().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton INSERTExit;
    private javax.swing.JPanel Insert;
    private javax.swing.JComboBox<String> InsertEntity;
    private javax.swing.JLabel InsertLabel;
    private javax.swing.JTabbedPane Main;
    private javax.swing.JButton SubmitEntity;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JPopupMenu jPopupMenu2;
    private javax.swing.JPopupMenu jPopupMenu3;
    private javax.swing.JPopupMenu jPopupMenu4;
    // End of variables declaration//GEN-END:variables
}
