/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package MIKA;

import MIKA.Mika;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ButtonGroup;

/**
 *
 * @author IRIS
 */
public class INSERTShipment extends javax.swing.JFrame {

    /**
     * Creates new form Shipment
     */
    public INSERTShipment() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup7 = new javax.swing.ButtonGroup();
        jComboBox1 = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        ShipID = new javax.swing.JLabel();
        Date = new javax.swing.JLabel();
        IRadio = new javax.swing.JRadioButton();
        DRadio = new javax.swing.JRadioButton();
        Content = new javax.swing.JLabel();
        DCombo = new javax.swing.JComboBox<>();
        IngCombo = new javax.swing.JComboBox<>();
        ShipIDField = new javax.swing.JTextField();
        DateField = new javax.swing.JTextField();
        Submit = new javax.swing.JButton();
        Status = new javax.swing.JLabel();
        Quantity = new javax.swing.JLabel();
        QField = new javax.swing.JTextField();
        Exit = new javax.swing.JButton();

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        ShipID.setText("Shipment ID");

        Date.setText("Delivery Date");

        buttonGroup7.add(IRadio);
        IRadio.setText("Ingredient");
        IRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IRadioActionPerformed(evt);
            }
        });

        buttonGroup7.add(DRadio);
        DRadio.setText("Disposable Item");
        DRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DRadioActionPerformed(evt);
            }
        });

        Content.setText("Contents:");

        DCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Napkin", "Spoon", "Fork", "Medium cup", "Large cup", "Medium cup lid", "Large cup lid", "Boxed container", "Straw", "Soup container" }));

        IngCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Milk", "Eggs", "Bacon", "Cheese", "Bread", "Spinach", "Salt", "Sugar", "Pepper", "Ham", "Tomato", "Broccoli", "Black Bean", "Tuna", "Turkey", "Onion", "Avocado", "Beef", "Kale", "Lettuce", "Apple", "Lemon", "Bottle Water", "San Pellegrino Orange", "Spindrift Raspberry Lime Seltzer", "Spindrift Lemon Seltzer", "Joia Grapefruit Soda", "Purity Organic Strawberry Paradise Juice", "San Pellegrino Sparkling Water", "Green tea", "Prickly Pear Hibiscus Fresca", "Blood Orange Lemonade", "Vegetable oil", "Chicken", "Arugula", "Steak" }));
        IngCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IngComboActionPerformed(evt);
            }
        });

        DateField.setText("YYYY-MM-DD");

        Submit.setText("Insert");
        Submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitActionPerformed(evt);
            }
        });

        Status.setText("Status....");

        Quantity.setText("Quantity");

        QField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                QFieldActionPerformed(evt);
            }
        });

        Exit.setText("Done");
        Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(IngCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Date)
                            .addComponent(ShipID)
                            .addComponent(Content))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(ShipIDField)
                                    .addComponent(DateField, javax.swing.GroupLayout.DEFAULT_SIZE, 371, Short.MAX_VALUE))
                                .addContainerGap(104, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(IRadio)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(DRadio)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addComponent(Quantity)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(QField, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 105, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(Status)
                        .addGap(85, 85, 85))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(DCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(63, 63, 63))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(Submit)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Exit)
                        .addGap(70, 70, 70))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ShipID)
                    .addComponent(ShipIDField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Date)
                    .addComponent(DateField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Content)
                    .addComponent(IRadio)
                    .addComponent(DRadio))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(IngCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Quantity)
                    .addComponent(QField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Submit)
                    .addComponent(Exit))
                .addGap(2, 2, 2)
                .addComponent(Status)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void DRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DRadioActionPerformed
        DCombo.setVisible(true);
        IngCombo.setVisible(false);
    }//GEN-LAST:event_DRadioActionPerformed

    private void IRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IRadioActionPerformed
        IngCombo.setVisible(true);
        DCombo.setVisible(false);
    }//GEN-LAST:event_IRadioActionPerformed

    private void SubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitActionPerformed
    Mika M = new Mika();
    if(ShipIDField.getText() == null || ShipIDField.getText().equals(""))
    {
        Status.setText("Failed. Type in a valid shipment ID.");
        return;
    }
    if(DateField.getText() == null || DateField.getText().equals(""))
    {
        Status.setText("Failed. Type in a valid date.");
        return;
    }
    if(DRadio.isSelected() == false && IRadio.isSelected() == false )
    {
        Status.setText("Failed. Please check one content.");
        return;
    }
    int shipID = Integer.parseInt(ShipIDField.getText());
    String date = "'" + DateField.getText() + "'";
    int DispID = 0;
    int IngID = 0;
    if(DRadio.isSelected())
    {
        try {
            DispID = M.getDispID("'" + DCombo.getSelectedItem().toString() + "'");
        } catch (Exception ex) {}
    }
    else
    {
        try {
            IngID = M.getIngID("'" + IngCombo.getSelectedItem().toString() + "'");
        } catch (Exception ex) {}
    }
    double quant = Double.parseDouble(QField.getText());
    try {
        M.insertIntoShipment(shipID, date, IngID, DispID, quant);
        Status.setText("Success!");

    } catch (Exception ex) {
        Status.setText("Failed. Try again.");
    }
   
    }//GEN-LAST:event_SubmitActionPerformed

    private void IngComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IngComboActionPerformed
        
    }//GEN-LAST:event_IngComboActionPerformed

    private void QFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_QFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_QFieldActionPerformed

    private void ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_ExitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(INSERTShipment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(INSERTShipment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(INSERTShipment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(INSERTShipment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new INSERTShipment().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Content;
    private javax.swing.JComboBox<String> DCombo;
    private javax.swing.JRadioButton DRadio;
    private javax.swing.JLabel Date;
    private javax.swing.JTextField DateField;
    private javax.swing.JButton Exit;
    private javax.swing.JRadioButton IRadio;
    private javax.swing.JComboBox<String> IngCombo;
    private javax.swing.JTextField QField;
    private javax.swing.JLabel Quantity;
    private javax.swing.JLabel ShipID;
    private javax.swing.JTextField ShipIDField;
    private javax.swing.JLabel Status;
    private javax.swing.JButton Submit;
    private javax.swing.ButtonGroup buttonGroup7;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
