/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package MIKA;

/**
 *
 * @author kalyanid
 */
public class SELECT extends javax.swing.JFrame {

    /**
     * Creates new form SELECT
     */
    public SELECT() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        VIEWOption = new javax.swing.JButton();
        INSERTOption = new javax.swing.JButton();
        UPDATEOption = new javax.swing.JButton();
        SELECTExit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        VIEWOption.setText("VIEW");
        VIEWOption.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VIEWOptionActionPerformed(evt);
            }
        });

        INSERTOption.setText("INSERT");
        INSERTOption.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                INSERTOptionActionPerformed(evt);
            }
        });

        UPDATEOption.setText("UPDATE");
        UPDATEOption.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UPDATEOptionActionPerformed(evt);
            }
        });

        SELECTExit.setText("Exit");
        SELECTExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SELECTExitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(SELECTExit)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(VIEWOption)
                        .addGap(56, 56, 56)
                        .addComponent(INSERTOption)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                .addComponent(UPDATEOption)
                .addGap(46, 46, 46))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(VIEWOption)
                    .addComponent(INSERTOption)
                    .addComponent(UPDATEOption))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 102, Short.MAX_VALUE)
                .addComponent(SELECTExit)
                .addGap(52, 52, 52))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void VIEWOptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VIEWOptionActionPerformed
        // TODO add your handling code here:
        new VIEW().setVisible(true);
    }//GEN-LAST:event_VIEWOptionActionPerformed

    private void INSERTOptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_INSERTOptionActionPerformed
        // TODO add your handling code here:
        new INSERT().setVisible(true);       
    }//GEN-LAST:event_INSERTOptionActionPerformed

    private void UPDATEOptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UPDATEOptionActionPerformed
        // TODO add your handling code here:
        new UPDATE().setVisible(true);        
    }//GEN-LAST:event_UPDATEOptionActionPerformed

    private void SELECTExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SELECTExitActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_SELECTExitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SELECT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SELECT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SELECT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SELECT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SELECT().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton INSERTOption;
    private javax.swing.JButton SELECTExit;
    private javax.swing.JButton UPDATEOption;
    private javax.swing.JButton VIEWOption;
    // End of variables declaration//GEN-END:variables
}
