/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package MIKA;

import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author IRIS
 */
public class UPDATE extends javax.swing.JFrame {

    /**
     * Creates new form MikaGUI
     */
    public UPDATE() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        jPopupMenu2 = new javax.swing.JPopupMenu();
        jPopupMenu3 = new javax.swing.JPopupMenu();
        jPopupMenu4 = new javax.swing.JPopupMenu();
        Main = new javax.swing.JTabbedPane();
        Update = new javax.swing.JPanel();
        UpdateEntity = new javax.swing.JComboBox<>();
        updateSubmit = new javax.swing.JButton();
        UPDATEExit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("UPDATE");

        UpdateEntity.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Menu Item", "Ingredients", "Disposable Items", "Employee" }));
        UpdateEntity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateEntityActionPerformed(evt);
            }
        });

        updateSubmit.setLabel("Submit");
        updateSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateSubmitActionPerformed(evt);
            }
        });

        UPDATEExit.setText("Exit");
        UPDATEExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UPDATEExitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout UpdateLayout = new javax.swing.GroupLayout(Update);
        Update.setLayout(UpdateLayout);
        UpdateLayout.setHorizontalGroup(
            UpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(UpdateLayout.createSequentialGroup()
                .addGroup(UpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(UpdateLayout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(UpdateEntity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(updateSubmit))
                    .addGroup(UpdateLayout.createSequentialGroup()
                        .addGap(140, 140, 140)
                        .addComponent(UPDATEExit)))
                .addContainerGap(129, Short.MAX_VALUE))
        );
        UpdateLayout.setVerticalGroup(
            UpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(UpdateLayout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(UpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(UpdateEntity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(updateSubmit))
                .addGap(74, 74, 74)
                .addComponent(UPDATEExit)
                .addContainerGap(75, Short.MAX_VALUE))
        );

        Main.addTab("Update", Update);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Main)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Main, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void UpdateEntityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateEntityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UpdateEntityActionPerformed

    private void updateSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateSubmitActionPerformed
      String entity = UpdateEntity.getSelectedItem().toString();
        switch(entity)
        {
            case "Menu Item":
            new UPDATEMenuItem().setVisible(true);
            break;
            case "Ingredients":
            new UPDATEIngredients().setVisible(true);
            break;
            case "Disposable Items":
            new UPDATEDisposableItem().setVisible(true);
            break;
            case "Employee":
            new UPDATEEmployee().setVisible(true);
            break;
        }
    }//GEN-LAST:event_updateSubmitActionPerformed

    private void UPDATEExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UPDATEExitActionPerformed
        // TODO add your handling code here:
        //this.dispose();
    }//GEN-LAST:event_UPDATEExitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UPDATE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UPDATE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UPDATE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UPDATE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UPDATE().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane Main;
    private javax.swing.JButton UPDATEExit;
    private javax.swing.JPanel Update;
    private javax.swing.JComboBox<String> UpdateEntity;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JPopupMenu jPopupMenu2;
    private javax.swing.JPopupMenu jPopupMenu3;
    private javax.swing.JPopupMenu jPopupMenu4;
    private javax.swing.JButton updateSubmit;
    // End of variables declaration//GEN-END:variables
}
